### ISSUE TITLE
Is there a Strict version of CBOR?

### ISSUE THREAD

**Issue by DeTeam** [orclev/CBOR#1]
Could you please correct me if I'm wrong, but current implementation works on top of lazy version of Get from binary package, which leads to handling parsing errors in IO monad instead of getting an Either, right?

What do you think about adding Strict version?

**Comment by orclev** [comment]
I'm not sure but I'll look into it when I get some free time. It's unlikely to happen anytime this week, but maybe sometime next week.

**Comment by DeTeam** [comment]
I'm not sure, too :) just wondered after reading article on binary package usage.

Tanks!
