### ISSUE TITLE
Publish on Hackage

### ISSUE THREAD

**Issue by DeTeam** [orclev/CBOR#2]
What do you think about that? :)

**Comment by orclev** [comment]
I'll consider it, but at the very least I want to finish off support for half-width floats. Currently that's blocked by the data-binary-ieee754 package only partially supporting them. To get around that I'll either need to wait till it gets updated or else create my own Get and Put instances for half-width floats. There's also a question of maintainership as I don't really have a lot of free time and I'm not sure I can devote the kind of time to keeping it updated on hackage that it would probably require.

**Comment by DeTeam** [comment]
I see. Thanks.
I'm pretty busy, too, but mb I can help you somehow, cause I find this package pretty clean (sources are awesome).

**Comment by orclev** [comment]
With the (admittedly half-assed) support I've added for opaque serialization of half-width floats I feel this is now in a state where I feel confident putting it up on hackage. I've started the process of getting upload permission on hackage and once that's granted I'll be putting this up there and closing this issue.
